[project]
name = "mcp-prompts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.17.0",
    "openai-agents>=0.3.3",
    "prompt-toolkit>=3.0.52",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
